insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Sep 12 2020', '%a %M %d %Y'), 'Fulham FC', '0-3', 'Arsenal FC', '1');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Sep 12 2020', '%a %M %d %Y'), 'Crystal Palace FC', '1-0', 'Southampton FC', '1');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Sep 12 2020', '%a %M %d %Y'), 'Liverpool FC', '4-3', 'Leeds United FC', '1');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Sep 12 2020', '%a %M %d %Y'), 'West Ham United FC', '0-2', 'Newcastle United FC', '1');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sun Sep 13 2020', '%a %M %d %Y'), 'West Bromwich Albion FC', '0-3', 'Leicester City FC', '1');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sun Sep 13 2020', '%a %M %d %Y'), 'Tottenham Hotspur FC', '0-1', 'Everton FC', '1');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Mon Sep 14 2020', '%a %M %d %Y'), 'Sheffield United FC', '0-2', 'Wolverhampton Wanderers FC', '1');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Mon Sep 14 2020', '%a %M %d %Y'), 'Brighton & Hove Albion FC', '1-3', 'Chelsea FC', '1');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Sep 19 2020', '%a %M %d %Y'), 'Everton FC', '5-2', 'West Bromwich Albion FC', '2');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Sep 19 2020', '%a %M %d %Y'), 'Leeds United FC', '4-3', 'Fulham FC', '2');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Sep 19 2020', '%a %M %d %Y'), 'Manchester United FC', '1-3', 'Crystal Palace FC', '2');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Sep 19 2020', '%a %M %d %Y'), 'Arsenal FC', '2-1', 'West Ham United FC', '2');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sun Sep 20 2020', '%a %M %d %Y'), 'Southampton FC', '2-5', 'Tottenham Hotspur FC', '2');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sun Sep 20 2020', '%a %M %d %Y'), 'Newcastle United FC', '0-3', 'Brighton & Hove Albion FC', '2');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sun Sep 20 2020', '%a %M %d %Y'), 'Chelsea FC', '0-2', 'Liverpool FC', '2');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sun Sep 20 2020', '%a %M %d %Y'), 'Leicester City FC', '4-2', 'Burnley FC', '2');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Mon Sep 21 2020', '%a %M %d %Y'), 'Aston Villa FC', '1-0', 'Sheffield United FC', '2');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Mon Sep 21 2020', '%a %M %d %Y'), 'Wolverhampton Wanderers FC', '1-3', 'Manchester City FC', '2');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Sep 26 2020', '%a %M %d %Y'), 'Brighton & Hove Albion FC', '2-3', 'Manchester United FC', '3');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Sep 26 2020', '%a %M %d %Y'), 'Crystal Palace FC', '1-2', 'Everton FC', '3');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Sep 26 2020', '%a %M %d %Y'), 'West Bromwich Albion FC', '3-3', 'Chelsea FC', '3');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Sep 26 2020', '%a %M %d %Y'), 'Burnley FC', '0-1', 'Southampton FC', '3');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sun Sep 27 2020', '%a %M %d %Y'), 'Sheffield United FC', '0-1', 'Leeds United FC', '3');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sun Sep 27 2020', '%a %M %d %Y'), 'Tottenham Hotspur FC', '1-1', 'Newcastle United FC', '3');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sun Sep 27 2020', '%a %M %d %Y'), 'Manchester City FC', '2-5', 'Leicester City FC', '3');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sun Sep 27 2020', '%a %M %d %Y'), 'West Ham United FC', '4-0', 'Wolverhampton Wanderers FC', '3');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Mon Sep 28 2020', '%a %M %d %Y'), 'Fulham FC', '0-3', 'Aston Villa FC', '3');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Mon Sep 28 2020', '%a %M %d %Y'), 'Liverpool FC', '3-1', 'Arsenal FC', '3');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Oct 3 2020', '%a %M %d %Y'), 'Chelsea FC', '4-0', 'Crystal Palace FC', '4');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Oct 3 2020', '%a %M %d %Y'), 'Everton FC', '4-2', 'Brighton & Hove Albion FC', '4');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Oct 3 2020', '%a %M %d %Y'), 'Leeds United FC', '1-1', 'Manchester City FC', '4');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Oct 3 2020', '%a %M %d %Y'), 'Newcastle United FC', '3-1', 'Burnley FC', '4');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sun Oct 4 2020', '%a %M %d %Y'), 'Leicester City FC', '0-3', 'West Ham United FC', '4');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sun Oct 4 2020', '%a %M %d %Y'), 'Southampton FC', '2-0', 'West Bromwich Albion FC', '4');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sun Oct 4 2020', '%a %M %d %Y'), 'Arsenal FC', '2-1', 'Sheffield United FC', '4');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sun Oct 4 2020', '%a %M %d %Y'), 'Wolverhampton Wanderers FC', '1-0', 'Fulham FC', '4');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sun Oct 4 2020', '%a %M %d %Y'), 'Manchester United FC', '1-6', 'Tottenham Hotspur FC', '4');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sun Oct 4 2020', '%a %M %d %Y'), 'Aston Villa FC', '7-2', 'Liverpool FC', '4');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Oct 17 2020', '%a %M %d %Y'), 'Everton FC', '2-2', 'Liverpool FC', '5');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Oct 17 2020', '%a %M %d %Y'), 'Chelsea FC', '3-3', 'Southampton FC', '5');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Oct 17 2020', '%a %M %d %Y'), 'Manchester City FC', '1-0', 'Arsenal FC', '5');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Oct 17 2020', '%a %M %d %Y'), 'Newcastle United FC', '1-4', 'Manchester United FC', '5');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sun Oct 18 2020', '%a %M %d %Y'), 'Sheffield United FC', '1-1', 'Fulham FC', '5');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sun Oct 18 2020', '%a %M %d %Y'), 'Crystal Palace FC', '1-1', 'Brighton & Hove Albion FC', '5');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sun Oct 18 2020', '%a %M %d %Y'), 'Tottenham Hotspur FC', '3-3', 'West Ham United FC', '5');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sun Oct 18 2020', '%a %M %d %Y'), 'Leicester City FC', '0-1', 'Aston Villa FC', '5');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Mon Oct 19 2020', '%a %M %d %Y'), 'West Bromwich Albion FC', '0-0', 'Burnley FC', '5');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Mon Oct 19 2020', '%a %M %d %Y'), 'Leeds United FC', '0-1', 'Wolverhampton Wanderers FC', '5');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Fri Oct 23 2020', '%a %M %d %Y'), 'Aston Villa FC', '0-3', 'Leeds United FC', '6');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Oct 24 2020', '%a %M %d %Y'), 'West Ham United FC', '1-1', 'Manchester City FC', '6');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Oct 24 2020', '%a %M %d %Y'), 'Fulham FC', '1-2', 'Crystal Palace FC', '6');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Oct 24 2020', '%a %M %d %Y'), 'Manchester United FC', '0-0', 'Chelsea FC', '6');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Oct 24 2020', '%a %M %d %Y'), 'Liverpool FC', '2-1', 'Sheffield United FC', '6');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sun Oct 25 2020', '%a %M %d %Y'), 'Southampton FC', '2-0', 'Everton FC', '6');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sun Oct 25 2020', '%a %M %d %Y'), 'Wolverhampton Wanderers FC', '1-1', 'Newcastle United FC', '6');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sun Oct 25 2020', '%a %M %d %Y'), 'Arsenal FC', '0-1', 'Leicester City FC', '6');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Mon Oct 26 2020', '%a %M %d %Y'), 'Brighton & Hove Albion FC', '1-1', 'West Bromwich Albion FC', '6');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Mon Oct 26 2020', '%a %M %d %Y'), 'Burnley FC', '0-1', 'Tottenham Hotspur FC', '6');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Fri Oct 30 2020', '%a %M %d %Y'), 'Wolverhampton Wanderers FC', '2-0', 'Crystal Palace FC', '7');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Oct 31 2020', '%a %M %d %Y'), 'Sheffield United FC', '0-1', 'Manchester City FC', '7');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Oct 31 2020', '%a %M %d %Y'), 'Burnley FC', '0-3', 'Chelsea FC', '7');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Oct 31 2020', '%a %M %d %Y'), 'Liverpool FC', '2-1', 'West Ham United FC', '7');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sun Nov 1 2020', '%a %M %d %Y'), 'Aston Villa FC', '3-4', 'Southampton FC', '7');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sun Nov 1 2020', '%a %M %d %Y'), 'Newcastle United FC', '2-1', 'Everton FC', '7');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sun Nov 1 2020', '%a %M %d %Y'), 'Manchester United FC', '0-1', 'Arsenal FC', '7');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sun Nov 1 2020', '%a %M %d %Y'), 'Tottenham Hotspur FC', '2-1', 'Brighton & Hove Albion FC', '7');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Mon Nov 2 2020', '%a %M %d %Y'), 'Fulham FC', '2-0', 'West Bromwich Albion FC', '7');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Mon Nov 2 2020', '%a %M %d %Y'), 'Leeds United FC', '1-4', 'Leicester City FC', '7');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Fri Nov 6 2020', '%a %M %d %Y'), 'Brighton & Hove Albion FC', '0-0', 'Burnley FC', '8');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Fri Nov 6 2020', '%a %M %d %Y'), 'Southampton FC', '2-0', 'Newcastle United FC', '8');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Nov 7 2020', '%a %M %d %Y'), 'Everton FC', '1-3', 'Manchester United FC', '8');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Nov 7 2020', '%a %M %d %Y'), 'Crystal Palace FC', '4-1', 'Leeds United FC', '8');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Nov 7 2020', '%a %M %d %Y'), 'Chelsea FC', '4-1', 'Sheffield United FC', '8');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Nov 7 2020', '%a %M %d %Y'), 'West Ham United FC', '1-0', 'Fulham FC', '8');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sun Nov 8 2020', '%a %M %d %Y'), 'West Bromwich Albion FC', '0-1', 'Tottenham Hotspur FC', '8');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sun Nov 8 2020', '%a %M %d %Y'), 'Leicester City FC', '1-0', 'Wolverhampton Wanderers FC', '8');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sun Nov 8 2020', '%a %M %d %Y'), 'Manchester City FC', '1-1', 'Liverpool FC', '8');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sun Nov 8 2020', '%a %M %d %Y'), 'Arsenal FC', '0-3', 'Aston Villa FC', '8');
