insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Sep 12 2020', '%a %M %d %Y'), 'Barrow AFC', '1-1', 'Stevenage FC', '1');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Sep 12 2020', '%a %M %d %Y'), 'Bolton Wanderers FC', '0-1', 'Forest Green Rovers FC', '1');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Sep 12 2020', '%a %M %d %Y'), 'Bradford City AFC', '0-0', 'Colchester United FC', '1');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Sep 12 2020', '%a %M %d %Y'), 'Cambridge United FC', '3-0', 'Carlisle United FC', '1');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Sep 12 2020', '%a %M %d %Y'), 'Cheltenham Town FC', '1-2', 'Morecambe FC', '1');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Sep 12 2020', '%a %M %d %Y'), 'Walsall FC', '1-0', 'Grimsby Town FC', '1');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Sep 12 2020', '%a %M %d %Y'), 'Mansfield Town FC', '0-0', 'Tranmere Rovers FC', '1');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Sep 12 2020', '%a %M %d %Y'), 'Oldham Athletic AFC', '0-1', 'Leyton Orient FC', '1');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Sep 12 2020', '%a %M %d %Y'), 'Port Vale FC', '2-0', 'Crawley Town FC', '1');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Sep 12 2020', '%a %M %d %Y'), 'Salford City FC', '2-2', 'Exeter City FC', '1');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Sep 12 2020', '%a %M %d %Y'), 'Scunthorpe United FC', '1-1', 'Newport County AFC', '1');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Sep 12 2020', '%a %M %d %Y'), 'Southend United FC', '0-4', 'Harrogate Town AFC', '1');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Sep 19 2020', '%a %M %d %Y'), 'Carlisle United FC', '2-0', 'Southend United FC', '2');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Sep 19 2020', '%a %M %d %Y'), 'Colchester United FC', '2-0', 'Bolton Wanderers FC', '2');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Sep 19 2020', '%a %M %d %Y'), 'Crawley Town FC', '1-0', 'Scunthorpe United FC', '2');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Sep 19 2020', '%a %M %d %Y'), 'Exeter City FC', '0-2', 'Port Vale FC', '2');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Sep 19 2020', '%a %M %d %Y'), 'Morecambe FC', '0-5', 'Cambridge United FC', '2');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Sep 19 2020', '%a %M %d %Y'), 'Stevenage FC', '3-0', 'Oldham Athletic AFC', '2');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Sep 19 2020', '%a %M %d %Y'), 'Forest Green Rovers FC', '2-2', 'Bradford City AFC', '2');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Sep 19 2020', '%a %M %d %Y'), 'Grimsby Town FC', '0-4', 'Salford City FC', '2');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Sep 19 2020', '%a %M %d %Y'), 'Harrogate Town AFC', '2-2', 'Walsall FC', '2');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Sep 19 2020', '%a %M %d %Y'), 'Leyton Orient FC', '2-2', 'Mansfield Town FC', '2');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Sep 19 2020', '%a %M %d %Y'), 'Newport County AFC', '2-1', 'Barrow AFC', '2');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Sep 19 2020', '%a %M %d %Y'), 'Tranmere Rovers FC', '0-3', 'Cheltenham Town FC', '2');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Sep 26 2020', '%a %M %d %Y'), 'Barrow AFC', '1-1', 'Colchester United FC', '3');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Sep 26 2020', '%a %M %d %Y'), 'Bolton Wanderers FC', '0-2', 'Newport County AFC', '3');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Sep 26 2020', '%a %M %d %Y'), 'Bradford City AFC', '2-1', 'Stevenage FC', '3');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Sep 26 2020', '%a %M %d %Y'), 'Cambridge United FC', '0-0', 'Tranmere Rovers FC', '3');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Sep 26 2020', '%a %M %d %Y'), 'Mansfield Town FC', '1-2', 'Exeter City FC', '3');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Sep 26 2020', '%a %M %d %Y'), 'Oldham Athletic AFC', '2-3', 'Crawley Town FC', '3');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Sep 26 2020', '%a %M %d %Y'), 'Port Vale FC', '0-0', 'Harrogate Town AFC', '3');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Sep 26 2020', '%a %M %d %Y'), 'Salford City FC', '0-0', 'Forest Green Rovers FC', '3');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Sep 26 2020', '%a %M %d %Y'), 'Scunthorpe United FC', '1-0', 'Carlisle United FC', '3');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Sep 26 2020', '%a %M %d %Y'), 'Southend United FC', '1-2', 'Morecambe FC', '3');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Oct 3 2020', '%a %M %d %Y'), 'Carlisle United FC', '1-0', 'Barrow AFC', '4');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Oct 3 2020', '%a %M %d %Y'), 'Colchester United FC', '3-3', 'Oldham Athletic AFC', '4');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Oct 3 2020', '%a %M %d %Y'), 'Crawley Town FC', '1-1', 'Southend United FC', '4');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Oct 3 2020', '%a %M %d %Y'), 'Exeter City FC', '2-0', 'Cambridge United FC', '4');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Oct 3 2020', '%a %M %d %Y'), 'Morecambe FC', '1-0', 'Port Vale FC', '4');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Oct 3 2020', '%a %M %d %Y'), 'Stevenage FC', '0-1', 'Salford City FC', '4');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Oct 3 2020', '%a %M %d %Y'), 'Forest Green Rovers FC', '1-1', 'Walsall FC', '4');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Oct 3 2020', '%a %M %d %Y'), 'Harrogate Town AFC', '1-2', 'Bolton Wanderers FC', '4');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Oct 3 2020', '%a %M %d %Y'), 'Leyton Orient FC', '0-2', 'Cheltenham Town FC', '4');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Oct 3 2020', '%a %M %d %Y'), 'Newport County AFC', '2-1', 'Mansfield Town FC', '4');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Oct 3 2020', '%a %M %d %Y'), 'Tranmere Rovers FC', '2-0', 'Scunthorpe United FC', '4');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Oct 10 2020', '%a %M %d %Y'), 'Barrow AFC', '1-1', 'Leyton Orient FC', '5');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Oct 10 2020', '%a %M %d %Y'), 'Bolton Wanderers FC', '0-0', 'Grimsby Town FC', '5');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Oct 10 2020', '%a %M %d %Y'), 'Cambridge United FC', '2-1', 'Newport County AFC', '5');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Oct 10 2020', '%a %M %d %Y'), 'Cheltenham Town FC', '2-0', 'Crawley Town FC', '5');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Oct 10 2020', '%a %M %d %Y'), 'Walsall FC', '1-1', 'Colchester United FC', '5');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Oct 10 2020', '%a %M %d %Y'), 'Mansfield Town FC', '0-0', 'Stevenage FC', '5');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Oct 10 2020', '%a %M %d %Y'), 'Oldham Athletic AFC', '2-3', 'Morecambe FC', '5');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Oct 10 2020', '%a %M %d %Y'), 'Port Vale FC', '0-1', 'Carlisle United FC', '5');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Oct 10 2020', '%a %M %d %Y'), 'Salford City FC', '2-2', 'Tranmere Rovers FC', '5');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Oct 10 2020', '%a %M %d %Y'), 'Scunthorpe United FC', '1-4', 'Forest Green Rovers FC', '5');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Oct 10 2020', '%a %M %d %Y'), 'Southend United FC', '2-2', 'Exeter City FC', '5');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Mon Oct 12 2020', '%a %M %d %Y'), 'Bradford City AFC', '0-1', 'Harrogate Town AFC', '5');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Tue Oct 13 2020', '%a %M %d %Y'), 'Cheltenham Town FC', '1-3', 'Grimsby Town FC', '3');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Tue Oct 13 2020', '%a %M %d %Y'), 'Walsall FC', '2-1', 'Leyton Orient FC', '3');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Oct 17 2020', '%a %M %d %Y'), 'Bolton Wanderers FC', '1-2', 'Oldham Athletic AFC', '6');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Oct 17 2020', '%a %M %d %Y'), 'Carlisle United FC', '3-2', 'Colchester United FC', '6');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Oct 17 2020', '%a %M %d %Y'), 'Crawley Town FC', '4-0', 'Morecambe FC', '6');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Oct 17 2020', '%a %M %d %Y'), 'Walsall FC', '0-0', 'Exeter City FC', '6');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Oct 17 2020', '%a %M %d %Y'), 'Forest Green Rovers FC', '1-0', 'Stevenage FC', '6');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Oct 17 2020', '%a %M %d %Y'), 'Harrogate Town AFC', '1-0', 'Barrow AFC', '6');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Oct 17 2020', '%a %M %d %Y'), 'Mansfield Town FC', '1-3', 'Bradford City AFC', '6');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Oct 17 2020', '%a %M %d %Y'), 'Newport County AFC', '1-0', 'Tranmere Rovers FC', '6');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Oct 17 2020', '%a %M %d %Y'), 'Port Vale FC', '1-0', 'Salford City FC', '6');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Oct 17 2020', '%a %M %d %Y'), 'Scunthorpe United FC', '0-5', 'Cambridge United FC', '6');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Oct 17 2020', '%a %M %d %Y'), 'Southend United FC', '0-2', 'Cheltenham Town FC', '6');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Oct 17 2020', '%a %M %d %Y'), 'Leyton Orient FC', '2-3', 'Grimsby Town FC', '6');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Tue Oct 20 2020', '%a %M %d %Y'), 'Cheltenham Town FC', '1-0', 'Scunthorpe United FC', '7');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Tue Oct 20 2020', '%a %M %d %Y'), 'Morecambe FC', '1-1', 'Mansfield Town FC', '7');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Tue Oct 20 2020', '%a %M %d %Y'), 'Barrow AFC', '3-3', 'Bolton Wanderers FC', '7');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Tue Oct 20 2020', '%a %M %d %Y'), 'Cambridge United FC', '3-1', 'Port Vale FC', '7');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Tue Oct 20 2020', '%a %M %d %Y'), 'Colchester United FC', '1-0', 'Forest Green Rovers FC', '7');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Tue Oct 20 2020', '%a %M %d %Y'), 'Exeter City FC', '2-1', 'Crawley Town FC', '7');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Tue Oct 20 2020', '%a %M %d %Y'), 'Stevenage FC', '0-1', 'Newport County AFC', '7');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Tue Oct 20 2020', '%a %M %d %Y'), 'Oldham Athletic AFC', '1-1', 'Carlisle United FC', '7');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Tue Oct 20 2020', '%a %M %d %Y'), 'Tranmere Rovers FC', '0-1', 'Leyton Orient FC', '7');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Tue Oct 20 2020', '%a %M %d %Y'), 'Bradford City AFC', '1-1', 'Walsall FC', '7');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Tue Oct 20 2020', '%a %M %d %Y'), 'Grimsby Town FC', '1-2', 'Harrogate Town AFC', '7');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Tue Oct 20 2020', '%a %M %d %Y'), 'Salford City FC', '3-0', 'Southend United FC', '7');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Oct 24 2020', '%a %M %d %Y'), 'Exeter City FC', '3-1', 'Scunthorpe United FC', '8');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Oct 24 2020', '%a %M %d %Y'), 'Barrow AFC', '2-2', 'Walsall FC', '8');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Oct 24 2020', '%a %M %d %Y'), 'Bradford City AFC', '0-3', 'Newport County AFC', '8');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Oct 24 2020', '%a %M %d %Y'), 'Cambridge United FC', '1-1', 'Bolton Wanderers FC', '8');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Oct 24 2020', '%a %M %d %Y'), 'Cheltenham Town FC', '0-0', 'Mansfield Town FC', '8');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Oct 24 2020', '%a %M %d %Y'), 'Colchester United FC', '2-1', 'Harrogate Town AFC', '8');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Oct 24 2020', '%a %M %d %Y'), 'Morecambe FC', '1-2', 'Forest Green Rovers FC', '8');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Oct 24 2020', '%a %M %d %Y'), 'Stevenage FC', '0-2', 'Leyton Orient FC', '8');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Oct 24 2020', '%a %M %d %Y'), 'Grimsby Town FC', '1-1', 'Carlisle United FC', '8');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Oct 24 2020', '%a %M %d %Y'), 'Oldham Athletic AFC', '1-2', 'Port Vale FC', '8');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Oct 24 2020', '%a %M %d %Y'), 'Salford City FC', '1-1', 'Crawley Town FC', '8');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Oct 24 2020', '%a %M %d %Y'), 'Tranmere Rovers FC', '2-0', 'Southend United FC', '8');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Tue Oct 27 2020', '%a %M %d %Y'), 'Crawley Town FC', '4-0', 'Tranmere Rovers FC', '9');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Tue Oct 27 2020', '%a %M %d %Y'), 'Carlisle United FC', '3-1', 'Morecambe FC', '9');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Tue Oct 27 2020', '%a %M %d %Y'), 'Walsall FC', '0-2', 'Cambridge United FC', '9');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Tue Oct 27 2020', '%a %M %d %Y'), 'Forest Green Rovers FC', '1-0', 'Grimsby Town FC', '9');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Tue Oct 27 2020', '%a %M %d %Y'), 'Harrogate Town AFC', '0-0', 'Stevenage FC', '9');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Tue Oct 27 2020', '%a %M %d %Y'), 'Leyton Orient FC', '1-1', 'Exeter City FC', '9');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Tue Oct 27 2020', '%a %M %d %Y'), 'Mansfield Town FC', '2-4', 'Barrow AFC', '9');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Tue Oct 27 2020', '%a %M %d %Y'), 'Newport County AFC', '2-1', 'Colchester United FC', '9');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Tue Oct 27 2020', '%a %M %d %Y'), 'Port Vale FC', '2-1', 'Cheltenham Town FC', '9');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Tue Oct 27 2020', '%a %M %d %Y'), 'Southend United FC', '1-2', 'Oldham Athletic AFC', '9');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Tue Oct 27 2020', '%a %M %d %Y'), 'Bolton Wanderers FC', '1-0', 'Bradford City AFC', '9');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Oct 31 2020', '%a %M %d %Y'), 'Exeter City FC', '1-0', 'Carlisle United FC', '10');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Oct 31 2020', '%a %M %d %Y'), 'Barrow AFC', '1-0', 'Bradford City AFC', '10');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Oct 31 2020', '%a %M %d %Y'), 'Cheltenham Town FC', '2-1', 'Forest Green Rovers FC', '10');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Oct 31 2020', '%a %M %d %Y'), 'Crawley Town FC', '2-1', 'Cambridge United FC', '10');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Oct 31 2020', '%a %M %d %Y'), 'Stevenage FC', '0-0', 'Grimsby Town FC', '10');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Oct 31 2020', '%a %M %d %Y'), 'Leyton Orient FC', '4-0', 'Bolton Wanderers FC', '10');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Oct 31 2020', '%a %M %d %Y'), 'Mansfield Town FC', '1-1', 'Walsall FC', '10');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Oct 31 2020', '%a %M %d %Y'), 'Newport County AFC', '2-1', 'Harrogate Town AFC', '10');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Oct 31 2020', '%a %M %d %Y'), 'Salford City FC', '2-0', 'Oldham Athletic AFC', '10');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Oct 31 2020', '%a %M %d %Y'), 'Southend United FC', '0-2', 'Port Vale FC', '10');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Oct 31 2020', '%a %M %d %Y'), 'Tranmere Rovers FC', '0-1', 'Morecambe FC', '10');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Tue Nov 3 2020', '%a %M %d %Y'), 'Oldham Athletic AFC', '2-1', 'Cheltenham Town FC', '11');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Tue Nov 3 2020', '%a %M %d %Y'), 'Morecambe FC', '2-2', 'Exeter City FC', '11');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Tue Nov 3 2020', '%a %M %d %Y'), 'Bradford City AFC', '3-0', 'Southend United FC', '11');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Tue Nov 3 2020', '%a %M %d %Y'), 'Cambridge United FC', '2-1', 'Salford City FC', '11');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Tue Nov 3 2020', '%a %M %d %Y'), 'Carlisle United FC', '3-2', 'Newport County AFC', '11');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Tue Nov 3 2020', '%a %M %d %Y'), 'Colchester United FC', '3-1', 'Stevenage FC', '11');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Tue Nov 3 2020', '%a %M %d %Y'), 'Walsall FC', '1-0', 'Crawley Town FC', '11');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Tue Nov 3 2020', '%a %M %d %Y'), 'Forest Green Rovers FC', '2-1', 'Leyton Orient FC', '11');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Tue Nov 3 2020', '%a %M %d %Y'), 'Grimsby Town FC', '1-0', 'Barrow AFC', '11');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Tue Nov 3 2020', '%a %M %d %Y'), 'Harrogate Town AFC', '0-1', 'Tranmere Rovers FC', '11');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Tue Nov 3 2020', '%a %M %d %Y'), 'Bolton Wanderers FC', '1-1', 'Mansfield Town FC', '11');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Fri Nov 13 2020', '%a %M %d %Y'), 'Bolton Wanderers FC', '2-0', 'Salford City FC', '12');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Nov 14 2020', '%a %M %d %Y'), 'Bradford City AFC', '2-2', 'Exeter City FC', '12');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Nov 14 2020', '%a %M %d %Y'), 'Cambridge United FC', '1-1', 'Barrow AFC', '12');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Nov 14 2020', '%a %M %d %Y'), 'Carlisle United FC', '1-2', 'Cheltenham Town FC', '12');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Nov 14 2020', '%a %M %d %Y'), 'Colchester United FC', '2-1', 'Leyton Orient FC', '12');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Nov 14 2020', '%a %M %d %Y'), 'Morecambe FC', '1-1', 'Stevenage FC', '12');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Nov 14 2020', '%a %M %d %Y'), 'Walsall FC', '0-1', 'Southend United FC', '12');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Nov 14 2020', '%a %M %d %Y'), 'Forest Green Rovers FC', '1-2', 'Mansfield Town FC', '12');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Nov 14 2020', '%a %M %d %Y'), 'Harrogate Town AFC', '1-1', 'Crawley Town FC', '12');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Nov 14 2020', '%a %M %d %Y'), 'Oldham Athletic AFC', '0-2', 'Scunthorpe United FC', '12');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Nov 14 2020', '%a %M %d %Y'), 'Port Vale FC', '3-4', 'Tranmere Rovers FC', '12');
