insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Fri Sep 11 2020', '%a %M %d %Y'), 'Watford FC', '1-0', 'Middlesbrough FC', '1');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Sep 12 2020', '%a %M %d %Y'), 'Birmingham City FC', '1-0', 'Brentford FC', '1');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Sep 12 2020', '%a %M %d %Y'), 'Wycombe Wanderers FC', '0-1', 'Rotherham United FC', '1');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Sep 12 2020', '%a %M %d %Y'), 'AFC Bournemouth', '3-2', 'Blackburn Rovers FC', '1');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Sep 12 2020', '%a %M %d %Y'), 'Bristol City FC', '2-1', 'Coventry City FC', '1');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Sep 12 2020', '%a %M %d %Y'), 'Cardiff City FC', '0-2', 'Sheffield Wednesday FC', '1');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Sep 12 2020', '%a %M %d %Y'), 'Derby County FC', '0-2', 'Reading FC', '1');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Sep 12 2020', '%a %M %d %Y'), 'Barnsley FC', '0-1', 'Luton Town FC', '1');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Sep 12 2020', '%a %M %d %Y'), 'Millwall FC', '0-0', 'Stoke City FC', '1');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Sep 12 2020', '%a %M %d %Y'), 'Huddersfield Town AFC', '0-1', 'Norwich City FC', '1');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Sep 12 2020', '%a %M %d %Y'), 'Preston North End FC', '0-1', 'Swansea City FC', '1');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Sep 12 2020', '%a %M %d %Y'), 'Queens Park Rangers FC', '2-0', 'Nottingham Forest FC', '1');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Fri Sep 18 2020', '%a %M %d %Y'), 'Coventry City FC', '3-2', 'Queens Park Rangers FC', '2');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Sep 19 2020', '%a %M %d %Y'), 'Nottingham Forest FC', '0-2', 'Cardiff City FC', '2');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Sep 19 2020', '%a %M %d %Y'), 'Blackburn Rovers FC', '5-0', 'Wycombe Wanderers FC', '2');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Sep 19 2020', '%a %M %d %Y'), 'Brentford FC', '3-0', 'Huddersfield Town AFC', '2');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Sep 19 2020', '%a %M %d %Y'), 'Middlesbrough FC', '1-1', 'AFC Bournemouth', '2');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Sep 19 2020', '%a %M %d %Y'), 'Reading FC', '2-0', 'Barnsley FC', '2');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Sep 19 2020', '%a %M %d %Y'), 'Luton Town FC', '2-1', 'Derby County FC', '2');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Sep 19 2020', '%a %M %d %Y'), 'Norwich City FC', '2-2', 'Preston North End FC', '2');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Sep 19 2020', '%a %M %d %Y'), 'Rotherham United FC', '0-1', 'Millwall FC', '2');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Sep 19 2020', '%a %M %d %Y'), 'Sheffield Wednesday FC', '0-0', 'Watford FC', '2');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Sep 19 2020', '%a %M %d %Y'), 'Swansea City FC', '0-0', 'Birmingham City FC', '2');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sun Sep 20 2020', '%a %M %d %Y'), 'Stoke City FC', '0-2', 'Bristol City FC', '2');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Fri Sep 25 2020', '%a %M %d %Y'), 'Huddersfield Town AFC', '1-0', 'Nottingham Forest FC', '3');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Sep 26 2020', '%a %M %d %Y'), 'Watford FC', '1-0', 'Luton Town FC', '3');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Sep 26 2020', '%a %M %d %Y'), 'Wycombe Wanderers FC', '0-2', 'Swansea City FC', '3');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Sep 26 2020', '%a %M %d %Y'), 'Birmingham City FC', '1-1', 'Rotherham United FC', '3');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Sep 26 2020', '%a %M %d %Y'), 'Cardiff City FC', '1-2', 'Reading FC', '3');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Sep 26 2020', '%a %M %d %Y'), 'Derby County FC', '0-4', 'Blackburn Rovers FC', '3');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Sep 26 2020', '%a %M %d %Y'), 'Barnsley FC', '0-0', 'Coventry City FC', '3');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Sep 26 2020', '%a %M %d %Y'), 'Millwall FC', '1-1', 'Brentford FC', '3');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Sep 26 2020', '%a %M %d %Y'), 'Preston North End FC', '0-1', 'Stoke City FC', '3');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Sep 26 2020', '%a %M %d %Y'), 'Queens Park Rangers FC', '1-1', 'Middlesbrough FC', '3');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sun Sep 27 2020', '%a %M %d %Y'), 'Bristol City FC', '2-0', 'Sheffield Wednesday FC', '3');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sun Sep 27 2020', '%a %M %d %Y'), 'AFC Bournemouth', '1-0', 'Norwich City FC', '3');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Fri Oct 2 2020', '%a %M %d %Y'), 'Coventry City FC', '1-3', 'AFC Bournemouth', '4');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Oct 3 2020', '%a %M %d %Y'), 'Norwich City FC', '0-1', 'Derby County FC', '4');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Oct 3 2020', '%a %M %d %Y'), 'Blackburn Rovers FC', '0-0', 'Cardiff City FC', '4');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Oct 3 2020', '%a %M %d %Y'), 'Middlesbrough FC', '2-1', 'Barnsley FC', '4');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Oct 3 2020', '%a %M %d %Y'), 'Reading FC', '1-0', 'Watford FC', '4');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Oct 3 2020', '%a %M %d %Y'), 'Luton Town FC', '2-0', 'Wycombe Wanderers FC', '4');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Oct 3 2020', '%a %M %d %Y'), 'Nottingham Forest FC', '1-2', 'Bristol City FC', '4');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Oct 3 2020', '%a %M %d %Y'), 'Rotherham United FC', '1-1', 'Huddersfield Town AFC', '4');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Oct 3 2020', '%a %M %d %Y'), 'Sheffield Wednesday FC', '1-1', 'Queens Park Rangers FC', '4');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Oct 3 2020', '%a %M %d %Y'), 'Swansea City FC', '2-1', 'Millwall FC', '4');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sun Oct 4 2020', '%a %M %d %Y'), 'Brentford FC', '2-4', 'Preston North End FC', '4');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sun Oct 4 2020', '%a %M %d %Y'), 'Stoke City FC', '1-1', 'Birmingham City FC', '4');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Fri Oct 16 2020', '%a %M %d %Y'), 'Derby County FC', '0-1', 'Watford FC', '5');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Oct 17 2020', '%a %M %d %Y'), 'AFC Bournemouth', '0-0', 'Queens Park Rangers FC', '5');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Oct 17 2020', '%a %M %d %Y'), 'Birmingham City FC', '0-1', 'Sheffield Wednesday FC', '5');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Oct 17 2020', '%a %M %d %Y'), 'Blackburn Rovers FC', '0-1', 'Nottingham Forest FC', '5');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Oct 17 2020', '%a %M %d %Y'), 'Barnsley FC', '2-2', 'Bristol City FC', '5');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Oct 17 2020', '%a %M %d %Y'), 'Brentford FC', '2-0', 'Coventry City FC', '5');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Oct 17 2020', '%a %M %d %Y'), 'Middlesbrough FC', '0-0', 'Reading FC', '5');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Oct 17 2020', '%a %M %d %Y'), 'Luton Town FC', '0-2', 'Stoke City FC', '5');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Oct 17 2020', '%a %M %d %Y'), 'Rotherham United FC', '1-2', 'Norwich City FC', '5');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Oct 17 2020', '%a %M %d %Y'), 'Swansea City FC', '1-2', 'Huddersfield Town AFC', '5');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Oct 17 2020', '%a %M %d %Y'), 'Wycombe Wanderers FC', '1-2', 'Millwall FC', '5');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sun Oct 18 2020', '%a %M %d %Y'), 'Preston North End FC', '0-1', 'Cardiff City FC', '5');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Tue Oct 20 2020', '%a %M %d %Y'), 'Bristol City FC', '0-1', 'Middlesbrough FC', '6');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Tue Oct 20 2020', '%a %M %d %Y'), 'Coventry City FC', '1-1', 'Swansea City FC', '6');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Tue Oct 20 2020', '%a %M %d %Y'), 'Millwall FC', '2-0', 'Luton Town FC', '6');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Tue Oct 20 2020', '%a %M %d %Y'), 'Norwich City FC', '1-0', 'Birmingham City FC', '6');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Tue Oct 20 2020', '%a %M %d %Y'), 'Nottingham Forest FC', '1-1', 'Rotherham United FC', '6');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Tue Oct 20 2020', '%a %M %d %Y'), 'Huddersfield Town AFC', '1-0', 'Derby County FC', '6');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Tue Oct 20 2020', '%a %M %d %Y'), 'Reading FC', '1-0', 'Wycombe Wanderers FC', '6');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Wed Oct 21 2020', '%a %M %d %Y'), 'Cardiff City FC', '1-1', 'AFC Bournemouth', '6');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Wed Oct 21 2020', '%a %M %d %Y'), 'Watford FC', '3-1', 'Blackburn Rovers FC', '6');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Wed Oct 21 2020', '%a %M %d %Y'), 'Queens Park Rangers FC', '0-2', 'Preston North End FC', '6');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Wed Oct 21 2020', '%a %M %d %Y'), 'Sheffield Wednesday FC', '1-2', 'Brentford FC', '6');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Wed Oct 21 2020', '%a %M %d %Y'), 'Stoke City FC', '2-2', 'Barnsley FC', '6');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Fri Oct 23 2020', '%a %M %d %Y'), 'Nottingham Forest FC', '1-1', 'Derby County FC', '7');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Oct 24 2020', '%a %M %d %Y'), 'Watford FC', '1-1', 'AFC Bournemouth', '7');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Oct 24 2020', '%a %M %d %Y'), 'Bristol City FC', '1-1', 'Swansea City FC', '7');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Oct 24 2020', '%a %M %d %Y'), 'Cardiff City FC', '1-1', 'Middlesbrough FC', '7');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Oct 24 2020', '%a %M %d %Y'), 'Coventry City FC', '0-4', 'Blackburn Rovers FC', '7');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Oct 24 2020', '%a %M %d %Y'), 'Millwall FC', '1-1', 'Barnsley FC', '7');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Oct 24 2020', '%a %M %d %Y'), 'Reading FC', '3-0', 'Rotherham United FC', '7');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Oct 24 2020', '%a %M %d %Y'), 'Huddersfield Town AFC', '1-2', 'Preston North End FC', '7');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Oct 24 2020', '%a %M %d %Y'), 'Norwich City FC', '2-1', 'Wycombe Wanderers FC', '7');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Oct 24 2020', '%a %M %d %Y'), 'Queens Park Rangers FC', '0-0', 'Birmingham City FC', '7');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Oct 24 2020', '%a %M %d %Y'), 'Sheffield Wednesday FC', '0-1', 'Luton Town FC', '7');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Oct 24 2020', '%a %M %d %Y'), 'Stoke City FC', '3-2', 'Brentford FC', '7');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Tue Oct 27 2020', '%a %M %d %Y'), 'Barnsley FC', '3-0', 'Queens Park Rangers FC', '8');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Tue Oct 27 2020', '%a %M %d %Y'), 'Blackburn Rovers FC', '2-4', 'Reading FC', '8');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Tue Oct 27 2020', '%a %M %d %Y'), 'Brentford FC', '1-1', 'Norwich City FC', '8');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Tue Oct 27 2020', '%a %M %d %Y'), 'Middlesbrough FC', '2-0', 'Coventry City FC', '8');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Tue Oct 27 2020', '%a %M %d %Y'), 'Swansea City FC', '2-0', 'Stoke City FC', '8');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Tue Oct 27 2020', '%a %M %d %Y'), 'Wycombe Wanderers FC', '1-1', 'Watford FC', '8');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Wed Oct 28 2020', '%a %M %d %Y'), 'Preston North End FC', '0-2', 'Millwall FC', '8');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Wed Oct 28 2020', '%a %M %d %Y'), 'AFC Bournemouth', '1-0', 'Bristol City FC', '8');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Wed Oct 28 2020', '%a %M %d %Y'), 'Birmingham City FC', '2-1', 'Huddersfield Town AFC', '8');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Wed Oct 28 2020', '%a %M %d %Y'), 'Derby County FC', '1-1', 'Cardiff City FC', '8');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Wed Oct 28 2020', '%a %M %d %Y'), 'Luton Town FC', '1-1', 'Nottingham Forest FC', '8');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Wed Oct 28 2020', '%a %M %d %Y'), 'Rotherham United FC', '3-0', 'Sheffield Wednesday FC', '8');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Fri Oct 30 2020', '%a %M %d %Y'), 'Coventry City FC', '3-2', 'Reading FC', '9');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Oct 31 2020', '%a %M %d %Y'), 'Bristol City FC', '1-3', 'Norwich City FC', '9');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Oct 31 2020', '%a %M %d %Y'), 'AFC Bournemouth', '1-1', 'Derby County FC', '9');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Oct 31 2020', '%a %M %d %Y'), 'Barnsley FC', '1-0', 'Watford FC', '9');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Oct 31 2020', '%a %M %d %Y'), 'Middlesbrough FC', '1-0', 'Nottingham Forest FC', '9');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Oct 31 2020', '%a %M %d %Y'), 'Millwall FC', '0-3', 'Huddersfield Town AFC', '9');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Oct 31 2020', '%a %M %d %Y'), 'Luton Town FC', '0-3', 'Brentford FC', '9');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Oct 31 2020', '%a %M %d %Y'), 'Preston North End FC', '1-2', 'Birmingham City FC', '9');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Oct 31 2020', '%a %M %d %Y'), 'Queens Park Rangers FC', '3-2', 'Cardiff City FC', '9');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Oct 31 2020', '%a %M %d %Y'), 'Stoke City FC', '1-0', 'Rotherham United FC', '9');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Oct 31 2020', '%a %M %d %Y'), 'Swansea City FC', '2-0', 'Blackburn Rovers FC', '9');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Oct 31 2020', '%a %M %d %Y'), 'Wycombe Wanderers FC', '1-0', 'Sheffield Wednesday FC', '9');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Tue Nov 3 2020', '%a %M %d %Y'), 'Brentford FC', '1-1', 'Swansea City FC', '10');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Tue Nov 3 2020', '%a %M %d %Y'), 'Huddersfield Town AFC', '1-2', 'Bristol City FC', '10');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Tue Nov 3 2020', '%a %M %d %Y'), 'Norwich City FC', '0-0', 'Millwall FC', '10');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Tue Nov 3 2020', '%a %M %d %Y'), 'Sheffield Wednesday FC', '1-0', 'AFC Bournemouth', '10');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Tue Nov 3 2020', '%a %M %d %Y'), 'Blackburn Rovers FC', '0-0', 'Middlesbrough FC', '10');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Tue Nov 3 2020', '%a %M %d %Y'), 'Cardiff City FC', '3-0', 'Barnsley FC', '10');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Wed Nov 4 2020', '%a %M %d %Y'), 'Watford FC', '3-2', 'Stoke City FC', '10');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Wed Nov 4 2020', '%a %M %d %Y'), 'Reading FC', '0-3', 'Preston North End FC', '10');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Wed Nov 4 2020', '%a %M %d %Y'), 'Birmingham City FC', '1-2', 'Wycombe Wanderers FC', '10');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Wed Nov 4 2020', '%a %M %d %Y'), 'Derby County FC', '0-1', 'Queens Park Rangers FC', '10');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Wed Nov 4 2020', '%a %M %d %Y'), 'Nottingham Forest FC', '2-1', 'Coventry City FC', '10');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Wed Nov 4 2020', '%a %M %d %Y'), 'Rotherham United FC', '0-1', 'Luton Town FC', '10');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Fri Nov 6 2020', '%a %M %d %Y'), 'Cardiff City FC', '0-1', 'Bristol City FC', '11');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Nov 7 2020', '%a %M %d %Y'), 'Reading FC', '0-3', 'Stoke City FC', '11');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Nov 7 2020', '%a %M %d %Y'), 'Birmingham City FC', '1-3', 'AFC Bournemouth', '11');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Nov 7 2020', '%a %M %d %Y'), 'Blackburn Rovers FC', '3-1', 'Queens Park Rangers FC', '11');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Nov 7 2020', '%a %M %d %Y'), 'Derby County FC', '0-2', 'Barnsley FC', '11');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Nov 7 2020', '%a %M %d %Y'), 'Brentford FC', '0-0', 'Middlesbrough FC', '11');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Nov 7 2020', '%a %M %d %Y'), 'Watford FC', '3-2', 'Coventry City FC', '11');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Nov 7 2020', '%a %M %d %Y'), 'Huddersfield Town AFC', '1-1', 'Luton Town FC', '11');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Nov 7 2020', '%a %M %d %Y'), 'Norwich City FC', '1-0', 'Swansea City FC', '11');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Nov 7 2020', '%a %M %d %Y'), 'Nottingham Forest FC', '2-0', 'Wycombe Wanderers FC', '11');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Nov 7 2020', '%a %M %d %Y'), 'Rotherham United FC', '2-1', 'Preston North End FC', '11');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Nov 7 2020', '%a %M %d %Y'), 'Sheffield Wednesday FC', '0-0', 'Millwall FC', '11');
