insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Sep 12 2020', '%a %M %d %Y'), 'Accrington Stanley FC', '2-0', 'Peterborough United FC', '1');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Sep 12 2020', '%a %M %d %Y'), 'Crewe Alexandra FC', '0-2', 'Charlton Athletic FC', '1');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Sep 12 2020', '%a %M %d %Y'), 'Doncaster Rovers FC', '1-1', 'Milton Keynes Dons FC', '1');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Sep 12 2020', '%a %M %d %Y'), 'Fleetwood Town FC', '2-1', 'Burton Albion FC', '1');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Sep 12 2020', '%a %M %d %Y'), 'Gillingham FC', '0-2', 'Hull City AFC', '1');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Sep 12 2020', '%a %M %d %Y'), 'Lincoln City FC', '2-0', 'Oxford United FC', '1');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Sep 12 2020', '%a %M %d %Y'), 'Northampton Town FC', '2-2', 'AFC Wimbledon', '1');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Sep 12 2020', '%a %M %d %Y'), 'Plymouth Argyle FC', '1-0', 'Blackpool FC', '1');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Sep 12 2020', '%a %M %d %Y'), 'Portsmouth FC', '0-0', 'Shrewsbury Town FC', '1');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Sep 12 2020', '%a %M %d %Y'), 'Sunderland AFC', '1-1', 'Bristol Rovers FC', '1');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Sep 12 2020', '%a %M %d %Y'), 'Swindon Town FC', '3-1', 'Rochdale AFC', '1');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sun Sep 13 2020', '%a %M %d %Y'), 'Ipswich Town FC', '2-0', 'Wigan Athletic FC', '1');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Sep 19 2020', '%a %M %d %Y'), 'AFC Wimbledon', '4-4', 'Plymouth Argyle FC', '2');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Sep 19 2020', '%a %M %d %Y'), 'Blackpool FC', '2-0', 'Swindon Town FC', '2');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Sep 19 2020', '%a %M %d %Y'), 'Bristol Rovers FC', '0-2', 'Ipswich Town FC', '2');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Sep 19 2020', '%a %M %d %Y'), 'Burton Albion FC', '2-1', 'Accrington Stanley FC', '2');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Sep 19 2020', '%a %M %d %Y'), 'Charlton Athletic FC', '1-3', 'Doncaster Rovers FC', '2');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Sep 19 2020', '%a %M %d %Y'), 'Hull City AFC', '1-0', 'Crewe Alexandra FC', '2');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Sep 19 2020', '%a %M %d %Y'), 'Milton Keynes Dons FC', '1-2', 'Lincoln City FC', '2');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Sep 19 2020', '%a %M %d %Y'), 'Oxford United FC', '0-2', 'Sunderland AFC', '2');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Sep 19 2020', '%a %M %d %Y'), 'Peterborough United FC', '2-1', 'Fleetwood Town FC', '2');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Sep 19 2020', '%a %M %d %Y'), 'Shrewsbury Town FC', '1-2', 'Northampton Town FC', '2');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Sep 19 2020', '%a %M %d %Y'), 'Wigan Athletic FC', '2-3', 'Gillingham FC', '2');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sun Sep 20 2020', '%a %M %d %Y'), 'Rochdale AFC', '0-0', 'Portsmouth FC', '2');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Sep 26 2020', '%a %M %d %Y'), 'Accrington Stanley FC', '1-4', 'Oxford United FC', '3');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Sep 26 2020', '%a %M %d %Y'), 'Crewe Alexandra FC', '2-0', 'Milton Keynes Dons FC', '3');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Sep 26 2020', '%a %M %d %Y'), 'Doncaster Rovers FC', '4-1', 'Bristol Rovers FC', '3');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Sep 26 2020', '%a %M %d %Y'), 'Fleetwood Town FC', '0-1', 'AFC Wimbledon', '3');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Sep 26 2020', '%a %M %d %Y'), 'Gillingham FC', '2-0', 'Blackpool FC', '3');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Sep 26 2020', '%a %M %d %Y'), 'Ipswich Town FC', '2-0', 'Rochdale AFC', '3');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Sep 26 2020', '%a %M %d %Y'), 'Northampton Town FC', '0-2', 'Hull City AFC', '3');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Sep 26 2020', '%a %M %d %Y'), 'Plymouth Argyle FC', '1-1', 'Shrewsbury Town FC', '3');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Sep 26 2020', '%a %M %d %Y'), 'Portsmouth FC', '1-2', 'Wigan Athletic FC', '3');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Sep 26 2020', '%a %M %d %Y'), 'Sunderland AFC', '1-0', 'Peterborough United FC', '3');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Sep 26 2020', '%a %M %d %Y'), 'Swindon Town FC', '4-2', 'Burton Albion FC', '3');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sun Sep 27 2020', '%a %M %d %Y'), 'Lincoln City FC', '2-0', 'Charlton Athletic FC', '3');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Oct 3 2020', '%a %M %d %Y'), 'AFC Wimbledon', '1-2', 'Accrington Stanley FC', '4');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Oct 3 2020', '%a %M %d %Y'), 'Blackpool FC', '2-3', 'Lincoln City FC', '4');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Oct 3 2020', '%a %M %d %Y'), 'Bristol Rovers FC', '2-0', 'Northampton Town FC', '4');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Oct 3 2020', '%a %M %d %Y'), 'Burton Albion FC', '2-4', 'Portsmouth FC', '4');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Oct 3 2020', '%a %M %d %Y'), 'Charlton Athletic FC', '0-0', 'Sunderland AFC', '4');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Oct 3 2020', '%a %M %d %Y'), 'Hull City AFC', '1-0', 'Plymouth Argyle FC', '4');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Oct 3 2020', '%a %M %d %Y'), 'Milton Keynes Dons FC', '1-1', 'Ipswich Town FC', '4');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Oct 3 2020', '%a %M %d %Y'), 'Peterborough United FC', '3-1', 'Swindon Town FC', '4');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Oct 3 2020', '%a %M %d %Y'), 'Rochdale AFC', '2-1', 'Fleetwood Town FC', '4');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Oct 3 2020', '%a %M %d %Y'), 'Shrewsbury Town FC', '1-1', 'Gillingham FC', '4');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Oct 3 2020', '%a %M %d %Y'), 'Wigan Athletic FC', '1-0', 'Doncaster Rovers FC', '4');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Fri Oct 9 2020', '%a %M %d %Y'), 'Fleetwood Town FC', '4-1', 'Hull City AFC', '5');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Oct 10 2020', '%a %M %d %Y'), 'Gillingham FC', '3-1', 'Oxford United FC', '5');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Oct 10 2020', '%a %M %d %Y'), 'Blackpool FC', '1-4', 'Ipswich Town FC', '12');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Oct 10 2020', '%a %M %d %Y'), 'Accrington Stanley FC', '2-1', 'Rochdale AFC', '5');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Oct 10 2020', '%a %M %d %Y'), 'Crewe Alexandra FC', '3-0', 'Wigan Athletic FC', '5');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Oct 10 2020', '%a %M %d %Y'), 'Lincoln City FC', '1-2', 'Bristol Rovers FC', '5');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Oct 10 2020', '%a %M %d %Y'), 'Northampton Town FC', '0-2', 'Peterborough United FC', '5');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Oct 10 2020', '%a %M %d %Y'), 'Plymouth Argyle FC', '2-0', 'Burton Albion FC', '5');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Oct 10 2020', '%a %M %d %Y'), 'Portsmouth FC', '2-1', 'Milton Keynes Dons FC', '5');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Oct 10 2020', '%a %M %d %Y'), 'Swindon Town FC', '0-1', 'AFC Wimbledon', '5');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Oct 17 2020', '%a %M %d %Y'), 'Milton Keynes Dons FC', '2-0', 'Gillingham FC', '6');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Oct 17 2020', '%a %M %d %Y'), 'AFC Wimbledon', '0-1', 'Shrewsbury Town FC', '6');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Oct 17 2020', '%a %M %d %Y'), 'Bristol Rovers FC', '1-1', 'Burton Albion FC', '6');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Oct 17 2020', '%a %M %d %Y'), 'Charlton Athletic FC', '1-0', 'Wigan Athletic FC', '6');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Oct 17 2020', '%a %M %d %Y'), 'Crewe Alexandra FC', '1-1', 'Blackpool FC', '6');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Oct 17 2020', '%a %M %d %Y'), 'Fleetwood Town FC', '0-0', 'Lincoln City FC', '6');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Oct 17 2020', '%a %M %d %Y'), 'Ipswich Town FC', '2-0', 'Accrington Stanley FC', '6');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Oct 17 2020', '%a %M %d %Y'), 'Peterborough United FC', '2-0', 'Oxford United FC', '6');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Oct 17 2020', '%a %M %d %Y'), 'Plymouth Argyle FC', '2-1', 'Northampton Town FC', '6');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Oct 17 2020', '%a %M %d %Y'), 'Portsmouth FC', '0-1', 'Doncaster Rovers FC', '6');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Oct 17 2020', '%a %M %d %Y'), 'Rochdale AFC', '0-3', 'Hull City AFC', '6');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Oct 17 2020', '%a %M %d %Y'), 'Swindon Town FC', '0-2', 'Sunderland AFC', '6');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Tue Oct 20 2020', '%a %M %d %Y'), 'Shrewsbury Town FC', '0-1', 'Bristol Rovers FC', '7');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Tue Oct 20 2020', '%a %M %d %Y'), 'Gillingham FC', '0-2', 'Portsmouth FC', '7');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Tue Oct 20 2020', '%a %M %d %Y'), 'Accrington Stanley FC', '1-0', 'Fleetwood Town FC', '7');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Tue Oct 20 2020', '%a %M %d %Y'), 'Blackpool FC', '0-1', 'Charlton Athletic FC', '7');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Tue Oct 20 2020', '%a %M %d %Y'), 'Hull City AFC', '1-0', 'AFC Wimbledon', '7');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Tue Oct 20 2020', '%a %M %d %Y'), 'Lincoln City FC', '2-0', 'Plymouth Argyle FC', '7');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Tue Oct 20 2020', '%a %M %d %Y'), 'Oxford United FC', '3-2', 'Milton Keynes Dons FC', '7');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Tue Oct 20 2020', '%a %M %d %Y'), 'Sunderland AFC', '1-0', 'Crewe Alexandra FC', '7');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Tue Oct 20 2020', '%a %M %d %Y'), 'Wigan Athletic FC', '0-1', 'Peterborough United FC', '7');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Tue Oct 20 2020', '%a %M %d %Y'), 'Doncaster Rovers FC', '4-1', 'Ipswich Town FC', '7');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Tue Oct 20 2020', '%a %M %d %Y'), 'Burton Albion FC', '0-1', 'Rochdale AFC', '7');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Tue Oct 20 2020', '%a %M %d %Y'), 'Northampton Town FC', '2-1', 'Swindon Town FC', '7');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Oct 24 2020', '%a %M %d %Y'), 'Gillingham FC', '0-2', 'Fleetwood Town FC', '8');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Oct 24 2020', '%a %M %d %Y'), 'Blackpool FC', '1-0', 'Milton Keynes Dons FC', '8');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Oct 24 2020', '%a %M %d %Y'), 'Burton Albion FC', '1-1', 'AFC Wimbledon', '8');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Oct 24 2020', '%a %M %d %Y'), 'Doncaster Rovers FC', '1-2', 'Crewe Alexandra FC', '8');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Oct 24 2020', '%a %M %d %Y'), 'Hull City AFC', '1-2', 'Peterborough United FC', '8');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Oct 24 2020', '%a %M %d %Y'), 'Lincoln City FC', '1-0', 'Ipswich Town FC', '8');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Oct 24 2020', '%a %M %d %Y'), 'Northampton Town FC', '0-2', 'Charlton Athletic FC', '8');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Oct 24 2020', '%a %M %d %Y'), 'Shrewsbury Town FC', '1-2', 'Rochdale AFC', '8');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Oct 24 2020', '%a %M %d %Y'), 'Sunderland AFC', '1-3', 'Portsmouth FC', '8');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Oct 24 2020', '%a %M %d %Y'), 'Wigan Athletic FC', '1-1', 'Plymouth Argyle FC', '8');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Tue Oct 27 2020', '%a %M %d %Y'), 'AFC Wimbledon', '1-0', 'Blackpool FC', '9');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Tue Oct 27 2020', '%a %M %d %Y'), 'Bristol Rovers FC', '1-3', 'Hull City AFC', '9');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Tue Oct 27 2020', '%a %M %d %Y'), 'Charlton Athletic FC', '2-0', 'Oxford United FC', '9');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Tue Oct 27 2020', '%a %M %d %Y'), 'Crewe Alexandra FC', '0-1', 'Lincoln City FC', '9');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Tue Oct 27 2020', '%a %M %d %Y'), 'Ipswich Town FC', '1-0', 'Gillingham FC', '9');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Tue Oct 27 2020', '%a %M %d %Y'), 'Milton Keynes Dons FC', '2-0', 'Wigan Athletic FC', '9');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Tue Oct 27 2020', '%a %M %d %Y'), 'Peterborough United FC', '2-2', 'Burton Albion FC', '9');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Tue Oct 27 2020', '%a %M %d %Y'), 'Fleetwood Town FC', '1-0', 'Shrewsbury Town FC', '9');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Tue Oct 27 2020', '%a %M %d %Y'), 'Plymouth Argyle FC', '2-1', 'Doncaster Rovers FC', '9');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Tue Oct 27 2020', '%a %M %d %Y'), 'Portsmouth FC', '4-0', 'Northampton Town FC', '9');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Tue Oct 27 2020', '%a %M %d %Y'), 'Rochdale AFC', '2-2', 'Sunderland AFC', '9');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Oct 31 2020', '%a %M %d %Y'), 'Gillingham FC', '0-2', 'Sunderland AFC', '10');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Oct 31 2020', '%a %M %d %Y'), 'Burton Albion FC', '1-2', 'Blackpool FC', '10');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Oct 31 2020', '%a %M %d %Y'), 'Doncaster Rovers FC', '1-0', 'Lincoln City FC', '10');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Oct 31 2020', '%a %M %d %Y'), 'Fleetwood Town FC', '2-0', 'Oxford United FC', '10');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Oct 31 2020', '%a %M %d %Y'), 'Ipswich Town FC', '1-0', 'Crewe Alexandra FC', '10');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Oct 31 2020', '%a %M %d %Y'), 'Milton Keynes Dons FC', '1-1', 'AFC Wimbledon', '10');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Oct 31 2020', '%a %M %d %Y'), 'Peterborough United FC', '5-1', 'Shrewsbury Town FC', '10');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Oct 31 2020', '%a %M %d %Y'), 'Portsmouth FC', '0-2', 'Charlton Athletic FC', '10');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Oct 31 2020', '%a %M %d %Y'), 'Rochdale AFC', '1-1', 'Bristol Rovers FC', '10');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Oct 31 2020', '%a %M %d %Y'), 'Swindon Town FC', '2-1', 'Hull City AFC', '10');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Oct 31 2020', '%a %M %d %Y'), 'Wigan Athletic FC', '2-3', 'Northampton Town FC', '10');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Tue Nov 3 2020', '%a %M %d %Y'), 'Shrewsbury Town FC', '1-1', 'Burton Albion FC', '11');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Tue Nov 3 2020', '%a %M %d %Y'), 'Blackpool FC', '1-0', 'Wigan Athletic FC', '11');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Tue Nov 3 2020', '%a %M %d %Y'), 'Bristol Rovers FC', '0-2', 'Peterborough United FC', '11');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Tue Nov 3 2020', '%a %M %d %Y'), 'Charlton Athletic FC', '3-2', 'Fleetwood Town FC', '11');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Tue Nov 3 2020', '%a %M %d %Y'), 'Crewe Alexandra FC', '0-1', 'Gillingham FC', '11');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Tue Nov 3 2020', '%a %M %d %Y'), 'Lincoln City FC', '1-3', 'Portsmouth FC', '11');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Tue Nov 3 2020', '%a %M %d %Y'), 'Oxford United FC', '3-1', 'Rochdale AFC', '11');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Tue Nov 3 2020', '%a %M %d %Y'), 'Plymouth Argyle FC', '4-2', 'Swindon Town FC', '11');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Tue Nov 3 2020', '%a %M %d %Y'), 'Sunderland AFC', '2-1', 'Ipswich Town FC', '11');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Tue Nov 3 2020', '%a %M %d %Y'), 'AFC Wimbledon', '2-2', 'Doncaster Rovers FC', '11');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Tue Nov 3 2020', '%a %M %d %Y'), 'Northampton Town FC', '0-0', 'Milton Keynes Dons FC', '11');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Nov 14 2020', '%a %M %d %Y'), 'Bristol Rovers FC', '1-4', 'Fleetwood Town FC', '12');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Nov 14 2020', '%a %M %d %Y'), 'Crewe Alexandra FC', '2-0', 'Peterborough United FC', '12');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Nov 14 2020', '%a %M %d %Y'), 'Hull City AFC', '2-0', 'Burton Albion FC', '12');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Nov 14 2020', '%a %M %d %Y'), 'Northampton Town FC', '0-1', 'Accrington Stanley FC', '12');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Nov 14 2020', '%a %M %d %Y'), 'Shrewsbury Town FC', '3-3', 'Swindon Town FC', '12');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Sat Nov 14 2020', '%a %M %d %Y'), 'Sunderland AFC', '1-2', 'Milton Keynes Dons FC', '12');
insert into matches.games(game_date, first_player, result, second_player, round)values (STR_TO_DATE('Mon Nov 16 2020', '%a %M %d %Y'), 'Plymouth Argyle FC', '2-2', 'Portsmouth FC', '12');
